#!/bin/bash
# (c) Roel Kluin, 2012, NKI

F="$1"
DN=$(dirname $0)

if [ ! -e "$1" ]; then
   $DN/facolor.pl "$@" 2>&1 | less -R
else
	shift;
	if [[ "$F" =~ \.gz$ ]]; then
		zcat "$F" | $DN/facolor.pl "$@" 2>&1 | less -R
	else
		cat "$F" | $DN/facolor.pl "$@" 2>&1 | less -R
	fi
fi
