#!/bin/bash
# (c) Roel Kluin, 2012, NKI

F="$1"

if [ ! -e "$1" ]; then
   ./facolor.pl "$@" | less -R
else
	shift;
	if [[ "$F" =~ \.gz$ ]]; then
		zcat "$F" | ./facolor.pl "$@" | less -R
	else
		cat "$F" | ./facolor.pl "$@" | less -R
	fi
fi
