#!/bin/bash
source $(dirname $0)/../environment.sh

die() {
  echo -e "$1"
  [ -z "$2" ] && exit 1 || exit $2;
}
USAGE="$0 [-B] [-m|--make <KEY_LENGTH>] [-L|--length <READLENGTH>] fasta.gz"

TEMP=`getopt -o m:L:B --long make:length:use-bwa -n "$0" -- "$@"`
if [ $? != 0 ]; then echo "Terminating..." >&2 ; exit 1 ; fi

# Note the quotes around `$TEMP': they are essential!
eval set -- "$TEMP"

USEBWA=
MAKE=
LENGTH=51
while true; do
  case "$1" in
    -m|--make) MAKE="$2"; shift;;
    -B|--use-bwa) USEBWA=1;;
    -L|--length) LENGTH="$2"; shift;;
    -- ) shift; break;;
    * ) break;;
  esac
  shift;
done
[ $# -ne 1 ] && die "$USAGE\n\nneed fasta.gz"
F="$1"
[ -e "$F" ] || "$USAGE\n\nno such file: $F"

[[ "$F" =~ \.gz$ ]] && BN="$(basename "$F" ".fa.gz")" || BN="$(basename "$F" ".fa")"
BA=${BN}-SE_true-RL_${LENGTH}.1

if [ -n "${USEBWA}" ]; then
  ls -lh ${BN}.fa.gz ../fakeq/${BN}-SE_true-RL_${LENGTH}.1.fastq.gz
  (time $bwa mem ${BN}.fa.gz ../fakeq/${BN}-SE_true-RL_${LENGTH}.1.fastq.gz | $samtools view -Sub - |
  $samtools sort - ${BA}.bwa) 2>&1 |tee ${BA}.bwa.log &&
  $samtools index ${BA}.bwa.bam
  $samtools view -H ${BA}.bwa.bam > ${BA}.1.hdr.sam
  exit 0;
fi
BA="${BA}.uqct"

# compile
if [ -n "$(find $hdesdir/* -maxdepth 0 -type f -regex ".*\/\(\(fa\|key_init\)\.cpp\|fa\.h\)" -amin -2)" ]; then
  echo $hdesdir/tst ${F} -c -m ${MAKE} -L ${LENGTH}
  $hdesdir/tst ${F} -c -m ${MAKE} -L ${LENGTH}
else
  cd $hdesdir;
  make clean
  DEFINES="-DKEY_LENGTH=${MAKE}" make;
  cd -
fi

BA=${BN}-SE_true-RL_${LENGTH}.1.uqct
if [ -f ${BA}.bam ]; then
  mv ${BA}.bam ${BA}_prev.bam
fi

time $hdesdir/uqct $hdesdir/fakeq/${BN}-SE_true-RL_${LENGTH}.1.fastq.gz ${F/.fa/.2b} -l ${LENGTH} |
$samtools view -Sub - |
$samtools sort -m 2000000000 - ${BA}

if [ ! -f "${BA}.bam" -o $(stat -c "%s" ${BA}.bam) -lt 10000 ]; then # revert
  mv ${BA}_prev.bam ${BA}.bam
  echo reverted
else # compare
  mv ${BA}.bam.bai ${BA}_prev.bam.bai
  $samtools index ${BA}.bam &&
diff -u <($samtools view ${BA}.bam)\
 <($samtools view ${BA}_prev.bam) |
 ./samdiff2batch.pl "${BA%.uqct}" > ${BN}.batchfile &&
 $igv -b ${BN}.batchfile
fi
#~/dev/git/IGV/igv.sh -g ../${BN}.fa ${BA}.bam


