#!/bin/bash
if [ "$(hostname)" = "Z" ]; then
  samtools=/home/roel/dev/git/samtools/lh3/samtools/samtools
else
  samtools=/net/NGSanalysis/apps/samtools/samtools-0.1.19/samtools
fi

# compile
if [ -n "$(find ../* -maxdepth 0 -type f -regex ".*\/\(fa\.cpp\|fa\.h\)" -amin -2)" ]; then
  ../tst hg19_GL.fa.gz -c -m 12
else
  cd ..;
  make clean 
  DEFINES="-DKEY_LENGTH=12" make;
  cd -
fi

if [ -f hg19_GL.1.uqct.bam ]; then
  mv hg19_GL.1.uqct.bam hg19_GL.1.uqct_prev.bam
fi

(cat hg19_GL.1.hdr.sam
../uqct ../fakeq/hg19_GL.1.fastq.gz ../hg19_GL.2b.gz -l 51) |
$samtools view -Sub - |
$samtools sort - hg19_GL.1.uqct

if [ ! -f "hg19_GL.1.uqct.bam" -o $(stat -c "%s" hg19_GL.1.uqct.bam) -lt 10000 ]; then # revert
  mv hg19_GL.1.uqct_prev.bam hg19_GL.1.uqct.bam
  echo reverted
else # compare
  mv hg19_GL.1.uqct.bam.bai hg19_GL.1.uqct_prev.bam.bai
  $samtools index hg19_GL.1.uqct.bam &&
diff -u <($samtools view hg19_GL.1.uqct.bam)\
 <($samtools view hg19_GL.1.uqct_prev.bam) |
 ./samdiff2batch.pl > batchfile &&
~/dev/git/IGV/igv.sh -b batchfile
fi



